name: Auto Issue Setting

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 이슈 생성자를 자동 할당
      - name: Auto-assign issue creator
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: ${{ github.actor }}

      # 클래식 프로젝트에 이슈 추가
      - name: Add issue to classic project
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          gh issue edit 8 --add-project "test" --user jaeml06
